### PR TITLE
Use moment to validate date/time's

### PR DESCRIPTION
**Pull request by Thor77**
This needs discussion imo, because it includes a workaround

### CODE REVIEW

**Comment by Thor77** [comment]
Rebased on master.

**Comment by wayneashleyberry** [comment]
@Thor77 might be getting formatting errors due to different versions of prettier?

**Comment by Thor77** [comment]
@wayneashleyberry might be, I'm running version `1.7.4` on my device.
Travis seems to fetch the same version, though. [ref](https://travis-ci.org/wayneashleyberry/wunderline/jobs/286529486#L483)

**Comment by wayneashleyberry** [comment]
@Thor77 would you mind pulling from master? I had to update prettier there and re-format the problematic code.

**Comment by Thor77** [comment]
@wayneashleyberry Done.

**Comment by wayneashleyberry** [comment]
Published as [v4.7.0](https://github.com/wayneashleyberry/wunderline/releases/tag/v4.7.0)

**Comment by Thor77** [comment]
Huh, you didn't squash my commits /o\\
Thanks, though 👍

**Comment by Thor77** [comment]
(copying my comment here as I accidentially posed it in another PR)

Argh, damnit, we need a hotfix... I assumed it would just work (because it did before) and couldn't test at work as I didn't have my credentials with me :( I will take care of that.

```
/home/x/workspace/node/wunderline/wunderline-add.js:102
    dueDate = dueDate.format("YYYY-MM-DD");
                      ^

TypeError: dueDate.format is not a function
```

Done in e5e7da50410107ebc82a926ac1b36c1b1b0c6d80
@wayneashleyberry Can you publish 4.7.1 to npm, please? I'm not really familiar with that process.

**Comment by wayneashleyberry** [comment]
Published as 4.7.2, I use [np](npm.im/np) which automatically bumps the version number :)

**Comment by Thor77** [comment]
Thank you 👍

**Pull request merged**
