### PR TITLE
feat: add wunderline-done command

### PR DESCRIPTION
**Pull request by marionebl**
**Included**:
-  adds basic updateTask lib function
-  displays filtered list based on initial user input
-  allows user to mark n tasks as completed
-  can be a boilerplate for more editing commands

**In action:**
wunderline-done-demo

### CODE REVIEW

**Comment by wayneashleyberry** [comment]
This looks great @marionebl - thank you!

**Comment by marionebl** [comment]
Any news on this?

**Comment by wayneashleyberry** [comment]
sorry @marionebl, got caught up with work.

how does one cancel the command once having invoked `wunderline done`?

escape and ctrl-c don't do anything

**Comment by marionebl** [comment]
Hey @wayneashleyberry, no worries just wanted to make sure this doesn't end in the crypt of forgotten pull requests. 

`C-c` cancels just fine for me – can you post some information about the system you are testing on? OS, OS version and used terminal emulator should suffice.

**Comment by wayneashleyberry** [comment]
```
iTerm 2 Build 3.0.1
```

```

                 -/+:.          Wayne@Users-iMac-3
                :++++.          OS: 64bit Mac OS X 10.11.5 15F34
               /+++/.           Kernel: x86_64 Darwin 15.5.0
       .:-::- .+/:-``.::-       Uptime: 10h 42m
    .:/++++++/::::/++++++/:`    Packages: 252
  .:///////////////////////:`   Shell: zsh 5.2
  ////////////////////////`     Resolution: 2560x1440 1920x1200
 -+++++++++++++++++++++++`      DE: Aqua
 /++++++++++++++++++++++/       WM: Quartz Compositor
 /sssssssssssssssssssssss.      WM Theme: Blue
 :ssssssssssssssssssssssss-     Font: MesloLGLDZ-Regular 14
  osssssssssssssssssssssssso/`  CPU: Intel Core i5 CPU 760 @ 2.80GHz
  `syyyyyyyyyyyyyyyyyyyyyyyy+`  GPU: ATI Radeon HD 5750
   `ossssssssssssssssssssss/    RAM: 6173MiB / 12288MiB
     :ooooooooooooooooooo+.
      `:+oo+/:-..-:/+o+/-

```

```
🍡  node -v
v6.2.2
```

```
🍡  npm -v
3.9.6
```

**Comment by wayneashleyberry** [comment]
My apologies @marionebl, I was invoking `./wunderline-done.js` directly.

It works fine when used as it should be, as a subcommand.

**Comment by wayneashleyberry** [comment]
Published as [v4.4.0](https://github.com/wayneashleyberry/wunderline/releases/tag/v4.4.0)

**Pull request merged**
