### PR TITLE
Match case sensitive if term contains uppercase letter

### LINKED ISSUE #80: Case sensitivity
If I have a list with e.g. `Current` and `current` listing on `Current` should not return `current`

### PR DESCRIPTION
**Pull request by rnc**
Closes #80

### CODE REVIEW

**Comment by Thor77** [comment]
Do you want to change your pull request according to the feedback in #80 or can I close this?

**Comment by Thor77** [comment]
If I don't receive feedback from @rnc in 3 days (14 days passed), I will close this.

**Comment by rnc** [comment]
@Thor77  Total apologies. Missed the email in the deluge from github. Updated

**Comment by Thor77** [comment]
Please fix [these](https://travis-ci.org/wayneashleyberry/wunderline/jobs/168129269#L495-L503) standard-violations.

**Comment by Thor77** [comment]
Great, thank you 🍪

**Pull request merged**
