### PR TITLE
Add --reminder flag to wunderline add

### LINKED ISSUE #72: Question: possible to set "Remind me" date?
Love wunderline, just love it. Thank you very much. Is there by any chance a way to set a "Remind me" date? It doesn't seem to be documented. (Or is it impossible?)

### PR DESCRIPTION
**Pull request by Thor77**
- if no valid datetime given (just time doesn't count as valid datetime), use dueDate

Do you think we should print an error and exit if no reminder-datetime given _and_ dueDate is invalid?
Additionally you should consider using `moment` to check for validity of `dueDate`.

Fix #72

### CODE REVIEW

**Comment by wayneashleyberry** [comment]
Hey @Thor77, would you mind resolving these conflicts? I'd like to get this in :)

**Comment by Thor77** [comment]
Rebased on master and added a small commit to print an error if an invalid datetime is given.
This PR depends on #100 , though, because it's already using `moment` for validity-checks, which will lead to warnings for invalid datetimes given to `--reminder`:
```
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: tomorrow, _f: undefined, _strict: undefined, _locale: [object Object]
```

**Comment by Thor77** [comment]
Uh, please don't merge this, yet, just found a regression related to #107 
Once adding multiple `--subtask`s **and** specifying a `--reminder`, node's async complains about calling the callback multiple times:
```
wunderline/node_modules/async/dist/async.js:844
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at wunderline/node_modules/async/dist/async.js:844:36
    at Request._callback (wunderline/wunderline-add.js:173:15)
    at Request.self.callback (wunderline/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (wunderline/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (wunderline/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
```
I first thought it would happen regardless of applying this PR but it doesn't before... Not sure, why, though, because the callback is called multiple times even without the `--reminder`-feature.
I guess my knowledge of node/javascript is too slim to understand that, can you take a look?

**Comment by wayneashleyberry** [comment]
Sure, I'll take a look this evening :) Would it make sense to merge #100 first?

**Comment by Thor77** [comment]
> Would it make sense to merge #100 first?

Yeah, definitely.

**Comment by Thor77** [comment]
Argh, damnit, we need a hotfix... I assumed it would just work (because it did before) and couldn't test at work as I didn't have my credentials with me :( I will take care of that.

```
/home/x/workspace/node/wunderline/wunderline-add.js:102
    dueDate = dueDate.format("YYYY-MM-DD");
                      ^

TypeError: dueDate.format is not a function
```

**Comment by Thor77** [comment]
Rebased on master.
Don't merge yet, please, though as
1. I didn't test it (as I'm at work again)
2. The collision issue between `--reminder` and `--subtask` is not fixed

**Comment by Thor77** [comment]
This PR is blocked by #113 (or at least until [ba1326dfd06e168ad446ac11ca24fb22834a69f2](https://github.com/wayneashleyberry/wunderline/pull/113/commits/ba1326dfd06e168ad446ac11ca24fb22834a69f2) is merged somehow).

**Comment by Thor77** [comment]
Should be ready for merge now.

**Review by wayneashleyberry — APPROVED** [review]

**Pull request merged**
