### PR TITLE
Subtask support

### PR DESCRIPTION
**Pull request by PSalant726**
Add support for creating subtasks when creating a new task.

### CODE REVIEW

**Comment by wayneashleyberry** [comment]
Hi @PSalant726 - and welcome :)

Firstly, thank you for this... it's been a long request feature.

Would you mind removing all of those semi-colons? This project adheres to the [standard](https://github.com/feross/standard) style. You can see details on the build if you click on the "Details" button next to the Travis build above or click here: https://travis-ci.org/wayneashleyberry/wunderline/jobs/220613850

You can run `npm test` to see the results on your machine.

**Comment by PSalant726** [comment]
Thanks for the review. I removed the semicolons and the test passes!

**Comment by Thor77** [comment]
Thanks for your PR!

Currently only one subtask is added despite giving `--subtask` multiple times.
To solve this you should use a custom function to collect all values given to the option.
For example as seen [here](https://stackoverflow.com/questions/30238654/commander-js-collect-multiple-options-always-include-default):
```javascript
function collect (value, memo) {
  memo.push(value)
  return memo
}
```
```javascript
.option('--subtask [task]', 'Add a subtask to the new task', collect, [])
```

Or use the solution given as an answer which could lead to issues with spaces in subtasks, though.

**Comment by PSalant726** [comment]
Thanks @Thor77 ! This is exactly what I was looking for. I added the function and updated the instructions to include a note about wrapping multi-word subtasks in `''`.

**Comment by wayneashleyberry** [comment]
I'm getting the following error when trying to test this out 

```sh
$ ./wunderline.js add 'Run Marathon' --subtask 'Train for marathon' --subtask 'Register for marathon'
```
```json
{
  "type": "missing_parameter",
  "translation_key": "api_error_missing_params",
  "message": "Missing parameter.",
  "title": [
    "required"
  ]
}
```

**Comment by Thor77** [comment]
> [...] and updated the instructions to include a note about wrapping multi-word subtasks in `''`

I don't think that's necessary, as that's already the case for any other option (like `--note` or even just the task name argument for `add`)

**Comment by PSalant726** [comment]
Sure, @Thor77, good point. I removed that extra bit.

@wayneashleyberry - I can't reproduce that error, but I also do not see my subtasks created when I run: 
`PATH=$(npm bin):$PATH wunderline add 'New test task' --subtask 'New test subtask 1' --subtask 'New test subtask 2' -o`
or
`PATH=$(npm bin):$PATH wunderline add 'New test task' --subtask 'New test subtask 1' -o`

I haven't worked on terminal commands before but I think there's an issue sending the `POST` request to the API. I thought I configured appropriately based on [these docs](https://developer.wunderlist.com/documentation/endpoints/subtask). Can you let me know if anything sticks out to you?

**Comment by Thor77** [comment]
@PSalant726 Thanks for the quick edit 👍 

If you can't reproduce @wayneashleyberry 's errors you're probably not running your latest local version of wunderline. The easiest way to to do that is probably to run `node wunderline.js [your options]` in your workspace.
Your problem is, that `app.subtask` is now an `array` instead of a `string` and therefore is not accepted as `title` by the wunderlist-api.
You have to iterate over this array (for example using [`forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)) and create a post-request to `/subtasks` for each element.

**Comment by PSalant726** [comment]
Right again @Thor77 !

I was able to reproduce the error. Additionally, after testing I noticed the subtasks are added to the new ToDo in reverse order, so I'm first using `.reverse()` on my subtasks array to make it more intuitive.

**Edit:** Instead of wasting space and time using `.reverse()` and saving to a new variable, now I'm just iterating backwards through `app.subtask`.

**Comment by wayneashleyberry** [comment]
This is looking great - thanks @PSalant726 :)

**Review by wayneashleyberry — COMMENTED** [review]
👍

**Comment by wayneashleyberry** [comment]
Published as [4.5.0](https://github.com/wayneashleyberry/wunderline/releases/tag/v4.5.0)! 🎉

**Comment by PSalant726** [comment]
Thanks @wayneashleyberry ! And thanks too to @Thor77 for all your help!

**Pull request merged**
